/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmountRow: typeof import('./src/components/ui/AmountRow.vue')['default']
    AnnouncementsCard: typeof import('./src/components/home/AnnouncementsCard.vue')['default']
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    AsyncShell: typeof import('./src/components/ui/AsyncShell.vue')['default']
    BrandLogo: typeof import('./src/components/ui/BrandLogo.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    CardHeader: typeof import('./src/components/ui/CardHeader.vue')['default']
    CelebrationsCard: typeof import('./src/components/home/CelebrationsCard.vue')['default']
    CheckinHero: typeof import('./src/components/home/CheckinHero.vue')['default']
    CommandPalette: typeof import('./src/components/layout/CommandPalette.vue')['default']
    DataTable: typeof import('./src/components/ui/DataTable.vue')['default']
    DateField: typeof import('./src/components/ui/DateField.vue')['default']
    DetailDrawer: typeof import('./src/components/ui/DetailDrawer.vue')['default']
    DocForm: typeof import('./src/components/ui/DocForm.vue')['default']
    DocList: typeof import('./src/components/ui/DocList.vue')['default']
    Drawer: typeof import('./src/components/ui/Drawer.vue')['default']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    Field: typeof import('./src/components/ui/Field.vue')['default']
    FilterChip: typeof import('./src/components/ui/FilterChip.vue')['default']
    FormDrawer: typeof import('./src/components/ui/FormDrawer.vue')['default']
    HolidaysCard: typeof import('./src/components/home/HolidaysCard.vue')['default']
    Icon: typeof import('./src/components/ui/Icon.vue')['default']
    InitialsAvatar: typeof import('./src/components/ui/InitialsAvatar.vue')['default']
    LeaveBalanceCard: typeof import('./src/components/home/LeaveBalanceCard.vue')['default']
    LinkControl: typeof import('./src/components/ui/LinkControl.vue')['default']
    MetricCard: typeof import('./src/components/ui/MetricCard.vue')['default']
    PageHeader: typeof import('./src/components/ui/PageHeader.vue')['default']
    PayslipMini: typeof import('./src/components/home/PayslipMini.vue')['default']
    ProgressBar: typeof import('./src/components/ui/ProgressBar.vue')['default']
    QuickActions: typeof import('./src/components/home/QuickActions.vue')['default']
    ReportDrawer: typeof import('./src/components/ui/ReportDrawer.vue')['default']
    Ring: typeof import('./src/components/home/Ring.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLabel: typeof import('./src/components/ui/SectionLabel.vue')['default']
    Segmented: typeof import('./src/components/ui/Segmented.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    StatTiles: typeof import('./src/components/ui/StatTiles.vue')['default']
    StatusBadge: typeof import('./src/components/ui/StatusBadge.vue')['default']
    Tabs: typeof import('./src/components/ui/Tabs.vue')['default']
    TasksCard: typeof import('./src/components/home/TasksCard.vue')['default']
    Toolbar: typeof import('./src/components/ui/Toolbar.vue')['default']
    Topbar: typeof import('./src/components/layout/Topbar.vue')['default']
    WeekStrip: typeof import('./src/components/home/WeekStrip.vue')['default']
    WhoIsOut: typeof import('./src/components/home/WhoIsOut.vue')['default']
  }
}
