<script setup>
import { computed } from "vue"
import {
  House,
  User,
  Users,
  CalendarCheck,
  Calendar,
  FileText,
  IndianRupee,
  Wallet,
  CreditCard,
  Target,
  CircleHelp,
  Megaphone,
  Inbox,
  LogIn,
  LogOut,
  ArrowUpRight,
  ArrowRight,
  Layers,
  Dot,
  Shield,
  Briefcase,
  LineChart,
  PieChart,
  SquarePen,
  Settings,
  Gift,
  Check,
  Plus,
  Search,
  Bell,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronsUpDown,
  Download,
  MapPin,
  Mail,
  Phone,
  ExternalLink,
  Clock,
  X,
  EllipsisVertical,
  Filter,
} from "lucide-vue-next"

// Prototype icon key -> lucide component. Single registry so screens reference
// stable string names (matching the prototype) instead of importing per-file.
const REGISTRY = {
  home: House,
  user: User,
  users: Users,
  calcheck: CalendarCheck,
  calendar: Calendar,
  file: FileText,
  rupee: IndianRupee,
  wallet: Wallet,
  card: CreditCard,
  target: Target,
  help: CircleHelp,
  megaphone: Megaphone,
  inbox: Inbox,
  login: LogIn,
  logout: LogOut,
  arrowUpRight: ArrowUpRight,
  arrowRight: ArrowRight,
  layers: Layers,
  dot: Dot,
  shield: Shield,
  briefcase: Briefcase,
  chart: LineChart,
  pieChart: PieChart,
  edit: SquarePen,
  settings: Settings,
  gift: Gift,
  check: Check,
  plus: Plus,
  search: Search,
  bell: Bell,
  chevDown: ChevronDown,
  chevRight: ChevronRight,
  chevLeft: ChevronLeft,
  chevUpDown: ChevronsUpDown,
  download: Download,
  mapPin: MapPin,
  mail: Mail,
  phone: Phone,
  external: ExternalLink,
  clock: Clock,
  x: X,
  moreV: EllipsisVertical,
  filter: Filter,
}

const props = defineProps({
  name: { type: String, required: true },
  size: { type: [Number, String], default: 18 },
  strokeWidth: { type: [Number, String], default: 1.75 },
})

const comp = computed(() => REGISTRY[props.name] || Dot)
</script>

<template>
  <component :is="comp" :size="Number(size)" :stroke-width="Number(strokeWidth)" />
</template>
